-- +goose Up
CREATE TABLE books (
    id UUID PRIMARY KEY,
    isbn VARCHAR(13) NOT NULL UNIQUE,
    title TEXT NOT NULL,
    author TEXT NOT NULL,
    num_pages INT NOT NULL,
    price INT NOT NULL
);

-- TODO: FIGURE OUT WHAT THE HELL IS GOING ON WITH SQLC AND WHY I NEEDED TO ADD PUBLISHER AND BOOK_DESC IN THIS OLD ASS MIGRATION



-- +goose Down
DROP TABLE books;