// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: books.sql

package database

import (
	"context"
	"database/sql"
)

const createBook = `-- name: CreateBook :one
INSERT INTO books (isbn, title, author, num_pages, price)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, isbn, title, author, num_pages, price
`

type CreateBookParams struct {
	Isbn     string
	Title    string
	Author   string
	NumPages sql.NullInt32
	Price    sql.NullInt32
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, createBook,
		arg.Isbn,
		arg.Title,
		arg.Author,
		arg.NumPages,
		arg.Price,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Isbn,
		&i.Title,
		&i.Author,
		&i.NumPages,
		&i.Price,
	)
	return i, err
}
