// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: books_generes.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createBooksGeneres = `-- name: CreateBooksGeneres :one
INSERT INTO books_generes (id, isbn, genere_id)
VALUES ($1, $2, $3)
RETURNING isbn, genere_id, id
`

type CreateBooksGeneresParams struct {
	ID       uuid.NullUUID
	Isbn     string
	GenereID uuid.UUID
}

func (q *Queries) CreateBooksGeneres(ctx context.Context, arg CreateBooksGeneresParams) (BooksGenere, error) {
	row := q.db.QueryRowContext(ctx, createBooksGeneres, arg.ID, arg.Isbn, arg.GenereID)
	var i BooksGenere
	err := row.Scan(&i.Isbn, &i.GenereID, &i.ID)
	return i, err
}
