// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: generes.sql

package database

import (
	"context"
	"database/sql"
)

const createGenere = `-- name: CreateGenere :one
INSERT INTO generes (name)
VALUES ($1)
RETURNING genere_id, name
`

func (q *Queries) CreateGenere(ctx context.Context, name sql.NullString) (Genere, error) {
	row := q.db.QueryRowContext(ctx, createGenere, name)
	var i Genere
	err := row.Scan(&i.GenereID, &i.Name)
	return i, err
}
