// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: gooks_generes.sql

package database

import (
	"context"
)

const createBookGenere = `-- name: CreateBookGenere :one
INSERT INTO books_generes (isbn, genere_id)
VALUES ($1, $2)
RETURNING id, isbn, genere_id
`

type CreateBookGenereParams struct {
	Isbn     string
	GenereID int32
}

func (q *Queries) CreateBookGenere(ctx context.Context, arg CreateBookGenereParams) (BooksGenere, error) {
	row := q.db.QueryRowContext(ctx, createBookGenere, arg.Isbn, arg.GenereID)
	var i BooksGenere
	err := row.Scan(&i.ID, &i.Isbn, &i.GenereID)
	return i, err
}
