// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: book_embeddings.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createEmbedding = `-- name: CreateEmbedding :one
INSERT INTO book_embeddings (id, book_id, embedding)
VALUES ($1, $2, $3)
RETURNING id, book_id, embedding
`

type CreateEmbeddingParams struct {
	ID        uuid.UUID
	BookID    uuid.UUID
	Embedding interface{}
}

func (q *Queries) CreateEmbedding(ctx context.Context, arg CreateEmbeddingParams) (BookEmbedding, error) {
	row := q.db.QueryRowContext(ctx, createEmbedding, arg.ID, arg.BookID, arg.Embedding)
	var i BookEmbedding
	err := row.Scan(&i.ID, &i.BookID, &i.Embedding)
	return i, err
}
